message_broker_rmq:
      build: server/.
      #image: rabbitmq:3.7-management
      container_name: shuniRabbit
      hostname: shuniRabbit
      ports:
        - 8080:15672
        - 5672:5672
      env_file:
        - './env/amq-settings'
      volumes:
        - ./shuniRabbit/rabbitmq_data:/var/lib/rabbitmq
        - ./shuniRabbit/var/log:/var/log
        - ./shuniRabbit/python_broker:/var/python_broker
      restart: always




